// <auto-generated />
namespace Project_Sem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cojko : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cojko));
        
        string IMigrationMetadata.Id
        {
            get { return "202302180426304_'co j ko'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
